development:
  sessions:
    default:
      database: wash_cost_app_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: wash_cost_app_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0

staging:
  sessions:
    default:
      database: wash_cost_app_staging
      hosts:
        - localhost:27017
      options:
        consistency: :strong
