development:
  sessions:
    default:
      database: wash_cost_app_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  sessions:
    default:
      database: wash_cost_app_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

staging:
  sessions:
    default:
      database: wash_cost_app_staging
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options:
        raise_not_found_error: false
        #consistency: :strong
        #max_retries: 1
        #retry_interval: 0